[package]
name = "indexical"
version = "0.1.0"
edition = "2021"

[package.metadata.rust-analyzer]
rustc_private = true

[features]
rustc = []
bitvec = ["dep:bitvec", "take_mut"]
default = ["bitvec"]

[dependencies]
bitvec = { version = "1.0.1", optional = true }
fxhash = "0.2.1"
index_vec = "0.1.3"
splitmut = "0.2.1"
take_mut = { version = "0.2.2", optional = true }
