name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Should be same as nightly used by current Flowistry
  NIGHTLY: nightly-2023-08-25

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ env.NIGHTLY }}
        components: rust-src, rustc-dev, llvm-tools-preview
    - name: Stable tests
      run: cargo test
    - name: Nightly tests
      run: cargo +${{ env.NIGHTLY }} test --features rustc

  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check formatting
      run: cargo fmt --check

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check lints
      run: cargo clippy --all -- -D warnings

    